# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
version = '1.5.1.dev160+gcffa780.d20211130'
version_tuple = (1, 5, 1, 'dev160', 'gcffa780.d20211130')
